title: Stackbit Azimuth Theme
baseURL: /
params:
  footer:
    content: '&copy; Steviebeenz. All rights reserved.'
    has_nav: true
    has_social: true
    has_subscribe: true
    links: []
    logo_img: images/logo_alt.png
    nav_title: Company
    social_title: Community
    subscribe_content: Stay up to date with our latest developments.
    subscribe_title: Subscribe
    tagline: Steviebeenz
  header:
    has_nav: true
    logo_img: ''
    title: Steviebeenz
    menu:
      actions:
        - label: Sign Up
          url: /signup
  palette: blue
disableKinds:
  - RSS
